# Site settings
title: Arduino Day
description: > # this means to ignore newlines until "baseurl:"
  Está chegando o Arduino Day 2019 Cachoeiro, um evento para reunir a comunidade local para discutir ideias e apresentar projetos que utilizem plataformas de prototipagem de baixo custo. Serão oferecidos minicursos, palestras e mostras de trabalhos. Fique atento à programação. Venha participar com a gente.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://arduinoday.github.io" # the base hostname & protocol for your site
author: "Labora"

# Build settings
markdown: kramdown
permalink: /posts/:title/
google_maps_javascript_api_key: "AIzaSyCdvKiZ7dmgeAGH3GicFsgkMdG0VtZbTew"

sass:
  style: compressed

# Contact info
contact:
  phone: (28) 3526-9033 | (28) 3526-9045
  email: arduinoday.ci@gmail.com
  address: Rodovia ES-482 (Cachoeiro-Alegre) - Fazenda Morro Grande, CEP 29311-970 - Cachoeiro de Itapemirim, ES - Brasil

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: ["Gemfile", "Gemfile.lock", "README.md"]